import Head from 'next/head'
import { useRouter } from 'next/router'
import styles from '../../../styles/Home.module.css'

export default function Home() {
  const { query } = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Dynamic Order Page
        </h1>

        <p>Order ID: {query.orderId}</p>
      </main>
    </div>
  )
}
